# Workaround for AWS:
# 1-st time it allows to login only as "ubuntu" user.
# It needs just overwrite "authorized_keys" file for root user - to allow remote root login.
# 
# For this special task, we must use "remote_user = ubuntu" to force login as "ubuntu" this time
#
- remote_user: ubuntu
  hosts: all
  # Adjusted for Hetzner: Ubuntu 16.04 has only python3 here:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
  - aws_allow_root_login
#
# Now we can proceed as always. Remote ROOT login should be already enabled.
#
- hosts: all
  # Adjusted for Hetzner: Ubuntu 16.04 has only python3 here:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
  - elk


