- name: Add Docker`s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add DOCKER Repository
  command: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

- name: Update APT with DOCKER Repository
  command: apt-get update  
  
- name: Install DOCKER engine
  apt: name={{ item }} state=installed
  with_items:
    - docker-ce

- debug:
    msg: "Adjusting Linux virtual memory setting for ELK:"

- lineinfile:
    dest: /etc/sysctl.conf
    line: 'vm.max_map_count = 262144'

- debug:
    msg: "Enable IPv4 port binding for Docker (step 1 of 3)"

- lineinfile:
    dest: /etc/sysctl.conf
    line: 'net.ipv6.conf.all.forwarding = 1'

- debug:
    msg: "Enable IPv4 port binding for Docker (step 2 of 3)"

- lineinfile:
    dest: /etc/sysctl.conf
    line: 'net.ipv6.bindv6only = 0'

- debug:
    msg: "Enable IPv4 port binding for Docker (step 3 of 3)"

- lineinfile:
    dest: /etc/sysctl.conf
    line: 'net.ipv4.ip_forward = 1'
    
- debug:
    msg: "Disabling IPv6 on host machine (step 1 of 3)"

- lineinfile:
    dest: /etc/sysctl.conf
    line: 'net.ipv6.conf.all.disable_ipv6 = 1'
    
- debug:
    msg: "Disabling IPv6 on host machine (step 2 of 3)"

- lineinfile:
    dest: /etc/sysctl.conf
    line: 'net.ipv6.conf.default.disable_ipv6 = 1'
    
- debug:
    msg: "Disabling IPv6 on host machine (step 3 of 3)"

- lineinfile:
    dest: /etc/sysctl.conf
    line: 'net.ipv6.conf.lo.disable_ipv6 = 1'
   
    
