- debug:
    msg: "Building ELK/GELF Docker image"

- name: Create ELK directory
  file: path=/opt/elk
        state=directory
        mode=0775

- name: Copy GELF config file
  copy: src=03-gelf-input.conf dest=/opt/elk/03-gelf-input.conf mode=0666
  
- name: Copy Dockerfile
  copy: src=Dockerfile dest=/opt/elk/Dockerfile mode=0666
  
- name: Copy build script
  copy: src=dockerbuild.sh dest=/opt/elk/dockerbuild.sh mode=0777

#- name: Building ELK/GELF Docker Image
#  command: /opt/elk/dockerbuild.sh

#- name: Starting ELK/GELF Docker image
#  command: docker run -p 80:5601 -p 9200:9200 -p 9300:9300 -p 12201:12201/udp --name elk1 wfelk
