# Setting up Firewall BEGIN------------------

#- name: Firewall saver
#  apt: pkg=netfilter-persistent state=installed

- name: Copy Firewall settings script
  template: src=root/iptables dest=~/iptables mode=0700

- name: Apply Firewall settings
  command: ~/iptables

- name: Make Firewall start at boot
  template: src=etc/network/if-pre-up.d/firewall_on dest=/etc/network/if-pre-up.d/firewall_on mode=0777

# Setting up Firewall END -------------------

#     https://askubuntu.com/questions/119393/how-to-save-rules-of-the-iptables !!!
