- debug:
    msg: "REBOOTING SERVER! Timezone and other stuff changed. All services must reload new settings!"

#- name: Restart server
#  become: yes
#  command: echo "sleep 3 ; reboot" | at now

- name: Copy reboot script
  copy: src=reboot.sh dest=/root/reboot.sh mode=0777

- name: Call reboot script
  command: /root/reboot.sh &

- name: waiting 20 secs for server to come back
  local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=20 timeout=60
  become: false
