- debug:
    msg: "REBOOTING SERVER! Timezone and other stuff changed. All services must reload new settings!"

- name: Restart server
  become: yes
  shell: sleep 2 && /sbin/shutdown -r now "Ansible stuff changed. Needs to reboot..."

- name: waiting 30 secs for server to come back
  local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=30 timeout=60
  become: false
