- debug:
    msg: "REBOOTING SERVER! Timezone and other stuff changed. All services must reload new settings!"

#- name: Restart server
#  become: yes
#  command: echo "sleep 3 ; reboot" | at now

#- name: Copy reboot script
#  copy: src=reboot.sh dest=/root/reboot.sh mode=0777

#- name: Call reboot script
#  command: /root/reboot.sh &
#- name: Call reboot script
#  shell: /root/reboot.sh 1>/dev/null 2>/dev/null

# !!!!!!!!!!!!!!!!!!!!!
#- name: Call reboot script
#  shell: shutdown -r 10:26 1>/dev/null 2>/dev/null

#!!!!!!!!!!!!!!!!!!!!
#!!!!!!!!!!!!!!!!!!!!
#- name: Schedule REBOOT in a minute...
#  shell: date --date="now +1 minute" +"%H:%M" | shutdown -r

- name: get current time
  command: /bin/date +%s
  register: before_reboot
#  sudo: false

- name: reboot system
  shell: sleep 2 && shutdown -r now "Reboot triggered by Ansible"
  async: 1
  poll: 0
  ignore_errors: true
  
- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=30 timeout=220
# sudo: false

- name: verify a reboot was actually initiated
  # machine should have started after it has been rebooted
  shell: (( `date +%s` - `awk -F . '{print $1}' /proc/uptime` > {{ before_reboot.stdout }} ))
#  sudo: false

#- name: waiting 70 secs for server to rebbot and come back
#  local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=70 timeout=120
#  become: false
