- debug:
    msg: "REBOOTING SERVER! Timezone and other stuff changed. All services must reload new settings!"

# Send the reboot command
- shell: shutdown -r now "Ansible stuff upgraded. Need to reboot" && sleep 2

# This pause is mandatory, otherwise the existing control connection gets reused!
- pause: seconds=30

# Now we will run a local 'ansible -m ping' on this host until it returns.
# This works with the existing ansible hosts inventory and so any custom ansible_ssh_hosts definitions are being used
- name: Waiting for server
  local_action: wait_for host={{ inventory_hostname }} state=started
